config/routes.rb
require 'sidekiq/web'
Pixelserve::Application.routes.draw do

  mount_activeadmin_settings

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount RedactorRails::Engine => '/redactor_rails'
  mount StripeEvent::Engine => '/stripe'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api, defaults: {format: 'json'} do
    ######################################################################################################################
    # API V1
    ######################################################################################################################
    namespace :v1 do
      resources :projects do
        member do
          put 'set_position'
          put 'toggle_favorite'
        end
        collection do
          put 'move'
        end
        resources :ctas
      end
      match 'survey_options', to: 'survey_options#create', via: [:post, :options]
      resources :videopages do
        member do
          get 'page'
          put 'save'
          put 'slug_save'
        end
      end
      resources :csns
      resources :assets do
        collection do
          get 'rackspace_url'
          get 'upload_form_params'
        end
        member do
          get 'copy_to_cloudfront'
          get 'start_encoding'
          get 'info_encoding'
          get 'is_finished'
          get 'retry_encoding'
        end
      end
      resources :plans
      resources :folders
      resources :billing do
        collection do
          post '/ipn/:id' => 'billing#ipn'
        end
      end

      resources :integrations do
        collection do
          get 'providers'
          get 'aweber_lists'
          get 'mailchimp_lists'
          get 'getresponse_campaigns'
          get 'csn_directories'
          get 'get_op_hosting_bucket'
          delete 'remove_file'
        end
      end

    end
    ######################################################################################################################
    # API V2
    ######################################################################################################################

    namespace :v2 do
      resources :projects do
        resources :ctas, only: [:index]
      end

      post 'survey_options' => 'survey_options#create'

      # third-party service integrations
      post 'mailchimp_subscribe' => 'mailchimp_integrations#subscribe'

      post 'aweber_subscribe' => 'aweber_integrations#subscribe'

      post 'getresponse_subscribe' => 'getresponse_integrations#subscribe'

      post 'stripe_purchase' => 'stripe_integrations#purchase'

      post 'paypal_purchase' => 'paypal_integrations#purchase'

      get 'paypal_callback' => 'paypal_integrations#callback', defaults: { format: 'html' }

      post 'purchase_callback' => 'purchase_delivery#callback'

    end
  end


  namespace :account do
    root to: 'main#index'

    post 'create_customer' => 'billing#create_customer'

    post 'update_card' => 'transactions#update_card'
    post 'update_plan' => 'transactions#update_plan'
    post 'buy_addon' => 'transactions#buy_addon'

    post 'apply_coupon' => 'subscriptions#apply_coupon'

    get 'team' => 'team_members#index'

    resources :accounts, only: [:update]
    resources :users

    resources :integrations do
      collection do
        get 'aweber_authorize'
        get 'aweber_oauth_callback'
      end
    end

    resources :team_members do
      collection do
        post 'invite'
      end
    end
    resources :billing
    resources :subscriptions do
      member do
        get 'cancel'
      end
    end
  end

  resources :csns, only: [:index] do
    member do
      get 'directories'
    end
  end

  resources :videos

  resources :projects do
    get 'export', on: :collection
    get 'load_player_code'
    member do
      get 'analytics'
    end
  end

  resources :videopages do
    # get 'preview'
  end
  get '/videopage/:id' => 'videopages#edit'

  resources :notifications, only: [:index, :mark_as_read] do
    member do
      put 'mark_as_read'
    end
  end

  resources :accounts

  match '/news/detail' => 'news#detail'
  match 'help' => 'main#help'
  match 'csn_message' => 'main#csn_message'

  # get '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get

  root to: "projects#index"

  post 'hide_welcome' => 'main#hide_welcome'

  devise_for :users, :controllers => {
                                      :registrations => 'registrations',
                                      :passwords => 'devise/passwords'
                                     }

  resources :videopages, :path => ''
  resources :videopages, :path => '', :only => [] do
  end
end

app/views/shared/_cloud_file_browser.html.haml
.clearfix
  .pull-left
    %h3 Select a file from your storage
  .pull-right.account-actions
    %select(selectpicker data-width="170px" ng-model="current_csn" ng-options="c.title for c in csns | filter: {provider: sourceType}")
.files-content.dsp-table
  .dsp-cell
    #uploading-status(ng-show="isLoadingFile")
      #uploading-progress
        %span
          Uploading video - {{percentage}}
        .progress.progress-striped.active
          .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "100", "aria-valuenow" => "100", :role => "progressbar", :style => "width: {{percentage}}"}
    #uploading-status(ng-show="!current_csn.buckets")
      #uploading-progress
        %span
          Downloading
        .progress.progress-striped.active
          .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "100", "aria-valuenow" => "100", :role => "progressbar", :style => "width: 100%"}
    %ul.list-unstyled.folders(ng-show="current_csn.buckets && !isLoadingFile")
      %li(ng-repeat="bucket in current_csn.buckets" ng-class="{selected: isHighlighted(bucket)}")
        %a(ng-click="setCurrentFolder(bucket, true)")
          {{bucket.name}}
        %ul(ng-tree="bucket.subdirs")
          %li(each="item in subdirs" ng-show="item.files.length > 0 || item.subdirs.length > 0" ng-class="{selected: isHighlighted(item)}")
            %a.folder(ng-click="setCurrentFolder(item)")
              {{item.name}}
    %div{style: "margin-left:15px;margin-bottom:5px;"}(upload-form ng-show="!isLoadingFile && current_csn.buckets")
      %csn-direct-upload(auto-upload="true" rc-type="public")
      %button.btn.btn-primary(ng-hide="!!uploadData" ng-click="browseFiles()") Upload a file
  .dsp-cell.files-list
    %form.navbar-form(role="search")
      %button.btn.btn-link(type="submit")
        = image_tag("icons/icon-search.png", width: "14")
      .form-group
        %input.form-control(type="text" placeholder="Search" ng-model="searchFile")
    %h3#list-reloading(ng-show="current_folder && current_folder.isBucket && !current_folder.loaded")
      .progress.progress-striped.active
        .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "100", "aria-valuenow" => "100", :role => "progressbar", :style => "width: 100%"}
    %ul.list-unstyled.files
      %li(ng-repeat="file in current_folder.files | filter: searchFile")
        %input(type="radio" id="amazon-file-{{$index + 1}}" name="select")
        %label(for="amazon-file-{{$index + 1}}" ng-click="setConnectedFile(file)") {{file.name}}

app/views/shared/_header.html.haml
#modal-widget-title.modal.fade.modal-widgets(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
  .modal-dialog
    .modal-content
      .modal-header
        %h4 Add a Title
      .modal-body
        %form
          .form-group
            %label Title
            %input.form-control(type="text" placeholder="Enter your title here")
          %ul.dsp-table.font-style
            %li.dsp-cell
              %select(selectpicker data-width="100%")
                %option Arial
                %option Helvetica
                %option Sans Serif
            %li.dsp-cell
              %select(selectpicker data-width="100%")
                %option Light
                %option Normal
                %option Bold
            %li.dsp-cell
              %input.font-size.form-control(type="text" value="18px")
          %ul.dsp-table
            %li.dsp-cell.color-input
              Text Color
              .input-group
                %i(style="background: #18D67F;")
                %input(type="text" value="#18D67F")
            %li.dsp-cell.color-input
              Background Color
              .input-group
                %i(style="background: #18D67F;")
                %input(type="text" value="#18D67F")
      .modal-footer
        %button.btn.btn-info(data-dismiss="modal") Cancel
        %button.btn.btn-primary Save

#modal-files.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
  .modal-dialog
    .modal-content(ng-controller="ProjectNewCtrl")
      %button.btn.btn-default.modal-dismiss(type="button" data-dismiss="modal" ng-click="loadInfo = false") Close
      %ul.nav.nav-tabs
        %li.active
          %a(href="#hosting" data-toggle="tab" ng-click="tab='hosting'") OptimizePlayer
        %li
          %a(href="#amazon" data-toggle="tab" ng-click="tab='amazon'") Amazon
        %li
          %a(href="#rackspace" data-toggle="tab" ng-click="tab='rackspace'") RackSpace
      .tab-content(csn-finder ng-cloak ng-controller="AssetUploadCtrl")
        #hosting.tab-pane.active
          .state-1
            .files-content.dsp-table
              .dsp-cell
                .drag-content#dropzone(ng-hide="isLoadingFile")
                  %h5 You can drag and drop files here
                  %span or
                  %csn-direct-upload(auto-upload="true" on-add="onFileAdd" on-progress-change="onProgressChange" on-done="onDone" on-fail="onFail" csn="opts.csnForUpload")
                  %a.btn.btn-primary(href="#" ng-click="browseUserFiles()") Browse
                #uploading-status(ng-show="isLoadingFile")
                  #uploading-progress
                    %span
                      Uploading video - {{percentage}}
                    .progress.progress-striped.active
                      .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "100", "aria-valuenow" => "100", :role => "progressbar", :style => "width: {{percentage}}"}
              .dsp-cell.files-list
                %form.navbar-form(role="search")
                  %button.btn.btn-link(type="submit")
                    = image_tag("icons/icon-search.png", width: "14")
                  .form-group
                    %input.form-control(type="text" placeholder="Search" ng-model="search")
                #uploading-status(ng-show="current_hosting_csn && current_hosting_csn.buckets == undefined")
                  #uploading-progress
                    %span
                      Downloading
                    .progress.progress-striped.active
                      .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "100", "aria-valuenow" => "100", :role => "progressbar", :style => "width: 100%"}
                #uploading-status(ng-show="current_hosting_folder.files == undefined && current_hosting_csn.buckets != undefined")
                  #uploading-progress
                    %span
                      There are no files...
                %ul.list-unstyled.files(ng-repeat="file in current_hosting_folder.files | filter: search")
                  %div
                    %li
                      %span(style="width:90%;")
                        %input(type="radio" id="file-{{$index + 1}}" name="select")
                        %label(for="file-{{$index + 1}}" ng-click="setHostingConnectedFile(file)") {{file.name}}
                      %span(style="float:right;")
                        %a.delete{"ng-click" => "deleteFile(file, $index)", :title => "Delete"}
                          %img{:alt => "Icon-delete", :src => "/assets/icons/icon-delete.png", :width => "11"}
        #amazon.tab-pane(ng-controller="IntegrationCtrl")
          .provider(ng-show="showS3Auth")
            %h4 Sign ln or Connect to Upload a Video
            #err
              %p{"ng-bind-html" => "invalidCredentialsMessage"}
            %input(type="text" placeholder="Nickname" ng-model="integration.api_credentials.title")
            %input(type="text" placeholder="Bucket" ng-model="integration.api_credentials.bucket")
            %input(type="text" placeholder="Access key" ng-model="integration.api_credentials.access_key_id")
            %input(type="text" placeholder="Secret Key" ng-model="integration.api_credentials.secret_access_key")
            %input#cloudfront(type="checkbox" ng-model="integration.api_credentials.use_cloudfront" )
            %label(for="cloudfront") Use Cloudfront
            %button.btn.btn-primary(ng-disabled="loading" type="submit" ng-click="saveIntegration()") Connect Provider
          %div(ng-show="!showS3Auth")
            = render 'shared/cloud_file_browser'
        #rackspace.tab-pane(ng-controller="IntegrationCtrl")
          .provider(ng-show="showRackspaceAuth")
            %h4 Sign ln or Connect to Upload a Video
            #err
              %p{"ng-bind-html" => "invalidCredentialsMessage"}
            %input(type="text" placeholder="Nickname" ng-model="integration.api_credentials.title")
            %input(type="text" placeholder="Container name" ng-model="integration.api_credentials.bucket")
            %input(type="text" placeholder="Username" ng-model="integration.api_credentials.username")
            %input(type="text" placeholder="Api Key" ng-model="integration.api_credentials.api_key")
            %button.btn.btn-primary(ng-disabled="loading" type="submit" ng-click="saveIntegration()") Connect Provider
          %div(ng-show="!showRackspaceAuth")
            = render 'shared/cloud_file_browser'
        .footer.clearfix(ng-show="goToNextStep")
          %div{style: "float:right;clear:right;"}
            %a.btn-primary.btn.submit-file(ng-click="toUpdatingProject()" ng-show="!inProgress") Select Video

= render "shared/modals/account"

#modal-notifications.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
  .modal-dialog
    .modal-content
      %ul.dsp-table
        %li.dsp-cell
          %h4 Latest Notifications
        %li.dsp-cell
          %a.close-notifications(href="#" data-dismiss="modal" ng-click="upward = 'notifications-off'")
            = image_tag("icons/icon-delete-gray.png", width: "15")
      #modal-notifications-content

%header(role="banner" ng-class="upward")
  %nav
    %ul.dsp-table
      %li.dsp-cell.logo
        %a(href="/" ng-click="reloadRoot()")
          = image_tag("logo.png", width: "184")
        #notifications_count
      %li.dsp-cell.search
        %form.navbar-form.navbar-left(action="/projects" method="get" role="search")
          %button.btn.btn-link(type="submit")
            = image_tag("icons/icon-search.png", width: "14")
          .form-group
            %input.form-control(name="search" placeholder="Search" type="text" value="#{@search}")/
      %li.dsp-cell.main-menu
        %ul.nav.nav-pills
          %li
            = link_to "My Projects", projects_path, class: ("active" if current_page?(projects_path))
          %li
            %a(href="#") Analytics
          %li
            = link_to "Help", "http://docs.optimizeplayer.com", target: "_blank"
          %li
            %a(href="#" data-toggle="modal" data-target="#modal-account") Account
          %li
            %a.btn.btn-primary(href="#" data-toggle="modal" data-target="#modal-files" ng-click="loadInfo = true") New Project